CREATE TABLE IF NOT EXISTS member_import_runs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NULL,
 year SMALLINT UNSIGNED NULL,
 source_name VARCHAR(255) NOT NULL,
 record_count INT UNSIGNED NOT NULL,
 created_count INT UNSIGNED NOT NULL DEFAULT 0,
 updated_count INT UNSIGNED NOT NULL DEFAULT 0,
 unchanged_count INT UNSIGNED NOT NULL DEFAULT 0,
 net_total DECIMAL(18,2) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS member_data_changes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 member_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NULL,
 action VARCHAR(40) NOT NULL,
 reason VARCHAR(500) NOT NULL,
 before_json JSON NULL,
 after_json JSON NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_member_change (member_id, id),
 FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
